# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0002_auto_20171110_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-created_time'], 'verbose_name': '\u83dc\u80b4', 'verbose_name_plural': '\u83dc\u80b4'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=models.TextField(blank=True, help_text='\u6ce8\uff1a\u76ee\u524d\u4ec5\u652f\u6301Markdown\u683c\u5f0f\u6570\u636e', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tags',
            field=models.ManyToManyField(related_name='menus', to='foodlist.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
