# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0003_auto_20171120_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='pv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='uv',
            field=models.IntegerField(default=0),
        ),
    ]
