# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0004_auto_20171128_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pv',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='uv',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
