# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodlist', '0005_auto_20171128_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='favorite',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf'),
        ),
    ]
