# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=16, verbose_name='\u5bc6\u7801')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('birth', models.DateField(auto_now_add=True, verbose_name='\u751f\u65e5')),
                ('sex', models.IntegerField(choices=[(0, '\u4fdd\u5bc6'), (1, '\u7537'), (2, '\u5973')], verbose_name='\u6027\u522b')),
                ('question', models.CharField(max_length=256, null=True, verbose_name='\u5bc6\u4fdd\u95ee\u9898')),
                ('answer', models.CharField(max_length=256, null=True, verbose_name='\u5bc6\u4fdd\u7b54\u6848')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u51bb\u7ed3'), (3, '\u5220\u9664')], verbose_name='\u7528\u6237\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7cfb\u7edf',
                'verbose_name_plural': '\u7528\u6237\u7cfb\u7edf',
            },
        ),
    ]
