# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.IntegerField(choices=[(0, '\u4fdd\u5bc6'), (1, '\u7537'), (2, '\u5973')], default=0, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u51bb\u7ed3'), (3, '\u5220\u9664')], default=1, verbose_name='\u7528\u6237\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
