# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.CharField(default='links', max_length=256, verbose_name='\u8bc4\u8bba\u76ee\u6807'),
        ),
    ]
