# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20171121_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, verbose_name='\u7f51\u7ad9'),
        ),
    ]
